<template>
  <div class="app-container">
    <el-form :inline="true" :model="queryParams" class="mb16"><el-form-item label="用户ID"><el-input v-model="queryParams.userId" style="width:180px" /></el-form-item><el-form-item label="风险等级"><el-select v-model="queryParams.riskLevel" clearable style="width:160px"><el-option label="低" value="LOW" /><el-option label="中" value="MEDIUM" /><el-option label="高" value="HIGH" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="getList">搜索</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-row :gutter="10" class="mb16"><el-col :span="1.5"><el-button type="primary" plain icon="Plus" @click="handleAdd">新增事件</el-button></el-col><el-col :span="1.5"><el-button type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()">修改</el-button></el-col><el-col :span="1.5"><el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">删除</el-button></el-col><right-toolbar v-model:showSearch="showSearch" @queryTable="getList" /></el-row>
    <el-table v-loading="loading" :data="dataList" @selection-change="handleSelectionChange"><el-table-column type="selection" width="55" /><el-table-column label="事件ID" prop="id" width="90" /><el-table-column label="用户ID" prop="userId" width="90" /><el-table-column label="登录IP" prop="loginIp" width="140" /><el-table-column label="风险类型" prop="riskType" width="120" /><el-table-column label="风险分" prop="riskScore" width="90" /><el-table-column label="风险等级" width="100"><template #default="scope"><el-tag :type="scope.row.riskLevel === 'HIGH' ? 'danger' : scope.row.riskLevel === 'MEDIUM' ? 'warning' : 'success'">{{ scope.row.riskLevel }}</el-tag></template></el-table-column><el-table-column label="处置状态" width="120"><template #default="scope"><el-tag>{{ scope.row.disposeStatus }}</el-tag></template></el-table-column><el-table-column label="登录时间" prop="loginTime" min-width="180" /><el-table-column label="操作" width="150"><template #default="scope"><el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)">修改</el-button><el-button link type="danger" icon="Delete" @click="handleDelete(scope.row)">删除</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog v-model="open" :title="title" width="760px"><el-form :model="form" label-width="100px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="用户ID"><el-input v-model="form.userId" /></el-form-item></el-col><el-col :span="12"><el-form-item label="登录IP"><el-input v-model="form.loginIp" /></el-form-item></el-col><el-col :span="12"><el-form-item label="登录地点"><el-input v-model="form.loginLocation" /></el-form-item></el-col><el-col :span="12"><el-form-item label="设备类型"><el-input v-model="form.deviceType" /></el-form-item></el-col><el-col :span="12"><el-form-item label="风险类型"><el-input v-model="form.riskType" /></el-form-item></el-col><el-col :span="12"><el-form-item label="风险分"><el-input v-model="form.riskScore" /></el-form-item></el-col><el-col :span="12"><el-form-item label="风险等级"><el-select v-model="form.riskLevel"><el-option label="低" value="LOW" /><el-option label="中" value="MEDIUM" /><el-option label="高" value="HIGH" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="处置动作"><el-input v-model="form.disposeAction" /></el-form-item></el-col><el-col :span="12"><el-form-item label="处置状态"><el-input v-model="form.disposeStatus" /></el-form-item></el-col><el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" rows="3" /></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="submitForm">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { addLoginRiskEvent, delLoginRiskEvent, getLoginRiskEvent, listLoginRiskEvent, updateLoginRiskEvent } from '@/api/campus/identity'
const loading=ref(false), showSearch=ref(true), total=ref(0), open=ref(false), title=ref(''), ids=ref<any[]>([]), single=ref(true), multiple=ref(true), dataList=ref<any[]>([])
const queryParams=reactive<any>({ pageNum:1,pageSize:10,userId:undefined,riskLevel:'' })
const form=reactive<any>({})
function resetForm(){ Object.assign(form,{ id:undefined,userId:undefined,loginIp:'',loginLocation:'',deviceType:'',riskType:'',riskScore:0,riskLevel:'LOW',disposeAction:'',disposeStatus:'PENDING',remark:'' }) }
async function getList(){ loading.value=true; const res=await listLoginRiskEvent(queryParams); dataList.value=res.rows||[]; total.value=res.total||0; loading.value=false }
function resetQuery(){ queryParams.pageNum=1; queryParams.userId=undefined; queryParams.riskLevel=''; getList() }
function handleSelectionChange(selection:any[]){ ids.value=selection.map(i=>i.id); single.value=selection.length!==1; multiple.value=!selection.length }
function handleAdd(){ resetForm(); title.value='新增风险事件'; open.value=true }
async function handleUpdate(row?:any){ resetForm(); const id=row?.id || ids.value[0]; if(!id) return; const res=await getLoginRiskEvent(id); Object.assign(form,res.data||{}); title.value='修改风险事件'; open.value=true }
async function submitForm(){ if(form.id){ await updateLoginRiskEvent(form); ElMessage.success('修改成功') } else { await addLoginRiskEvent(form); ElMessage.success('新增成功') } open.value=false; getList() }
async function handleDelete(row?:any){ const target=row?.id || ids.value; if(!target || (Array.isArray(target)&&!target.length)) return; await ElMessageBox.confirm('确认删除所选风险事件吗？','提示',{type:'warning'}); await delLoginRiskEvent(target); ElMessage.success('删除成功'); getList() }
resetForm(); getList()
</script>
<style scoped>.mb16{margin-bottom:16px}</style>
