CREATE TABLE IF NOT EXISTS sc_learning_task (
  task_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  task_title VARCHAR(120) NOT NULL COMMENT '任务标题',
  task_type VARCHAR(30) NOT NULL COMMENT '任务类型(HOMEWORK/EXAM/PRACTICE/READING/COURSE)',
  biz_type VARCHAR(30) DEFAULT NULL COMMENT '业务类型',
  biz_id BIGINT DEFAULT NULL COMMENT '业务ID',
  course_id BIGINT DEFAULT NULL COMMENT '课程ID',
  class_course_id BIGINT DEFAULT NULL COMMENT '班级课程ID',
  term_id BIGINT DEFAULT NULL COMMENT '学期ID',
  task_desc VARCHAR(1000) DEFAULT NULL COMMENT '任务描述',
  priority_level VARCHAR(20) DEFAULT 'NORMAL' COMMENT '优先级',
  action_type VARCHAR(30) DEFAULT NULL COMMENT '动作类型',
  action_path VARCHAR(255) DEFAULT NULL COMMENT '动作路径',
  action_target_id BIGINT DEFAULT NULL COMMENT '动作目标ID',
  publish_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  start_time DATETIME DEFAULT NULL COMMENT '开始时间',
  due_time DATETIME DEFAULT NULL COMMENT '截止时间',
  status CHAR(1) DEFAULT '0' COMMENT '状态(0正常 1停用)',
  target_scope VARCHAR(30) DEFAULT 'USER' COMMENT '派发范围',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习任务主表';

CREATE TABLE IF NOT EXISTS sc_learning_task_dispatch (
  dispatch_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '派发ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  dispatch_status CHAR(1) DEFAULT '0' COMMENT '派发状态(0有效 1取消)',
  completion_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '完成状态',
  completed_time DATETIME DEFAULT NULL COMMENT '完成时间',
  read_time DATETIME DEFAULT NULL COMMENT '阅读时间',
  completion_remark VARCHAR(500) DEFAULT NULL COMMENT '完成说明',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (dispatch_id),
  UNIQUE KEY uk_task_user (task_id, user_id),
  KEY idx_dispatch_user (user_id, dispatch_status, completion_status),
  CONSTRAINT fk_learning_task_dispatch_task FOREIGN KEY (task_id) REFERENCES sc_learning_task(task_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习任务派发表';

CREATE TABLE IF NOT EXISTS sc_learning_task_submission (
  submission_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '提交ID',
  dispatch_id BIGINT NOT NULL COMMENT '派发ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  submit_content TEXT COMMENT '提交内容',
  attachment_urls TEXT COMMENT '附件地址(JSON数组字符串)',
  submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
  review_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '批阅状态',
  score DECIMAL(6,2) DEFAULT NULL COMMENT '得分',
  teacher_feedback VARCHAR(1000) DEFAULT NULL COMMENT '教师反馈',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (submission_id),
  UNIQUE KEY uk_dispatch_submission (dispatch_id),
  KEY idx_submission_task_user (task_id, user_id),
  CONSTRAINT fk_learning_task_submission_dispatch FOREIGN KEY (dispatch_id) REFERENCES sc_learning_task_dispatch(dispatch_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习任务提交回执表';
