/*
 Navicat Premium Dump SQL

 Source Server         : 本地数据库
 Source Server Type    : MySQL
 Source Server Version : 80040 (8.0.40)
 Source Host           : localhost:3306
 Source Schema         : smart_campus

 Target Server Type    : MySQL
 Target Server Version : 80040 (8.0.40)
 File Encoding         : 65001

 Date: 30/03/2026 12:46:43
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for sc_affair_template
-- ----------------------------
DROP TABLE IF EXISTS `sc_affair_template`;
CREATE TABLE `sc_affair_template`  (
  `template_id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板ID',
  `category_id` bigint NOT NULL COMMENT '事务分类ID',
  `template_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '模板名称',
  `business_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '业务编码',
  `business_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '业务名称',
  `audience_roles` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'student' COMMENT '可发起角色',
  `form_schema_json` json NULL COMMENT '表单Schema',
  `workflow_schema_json` json NULL COMMENT '流程Schema',
  `allow_attachment` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '是否允许附件（0否 1是）',
  `allow_revoke` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '1' COMMENT '是否允许撤回（0否 1是）',
  `apply_scope_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '申请范围配置JSON',
  `business_rules_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务规则配置JSON',
  `target_status_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '目标学籍状态编码',
  `target_status_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '目标学籍状态名称',
  `sort_order` int NULL DEFAULT 0 COMMENT '排序',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '状态（0正常 1停用）',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`template_id`) USING BTREE,
  UNIQUE INDEX `uk_sc_affair_template_code`(`template_code` ASC) USING BTREE,
  INDEX `idx_sc_affair_template_category_id`(`category_id` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 18 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '学生事务模板表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of sc_affair_template
-- ----------------------------
INSERT INTO `sc_affair_template` VALUES (1, 1, 'ASK_LEAVE_STANDARD', '学生请销假申请', 'ASK_LEAVE_STANDARD', '学生请销假申请', 'student', '[{\"field\": \"leaveType\", \"label\": \"请假类型\", \"options\": [{\"label\": \"事假\", \"value\": \"PERSONAL\"}, {\"label\": \"病假\", \"value\": \"SICK\"}, {\"label\": \"公假\", \"value\": \"OFFICIAL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"startDate\", \"label\": \"开始时间\", \"required\": true, \"component\": \"date\"}, {\"field\": \"endDate\", \"label\": \"结束时间\", \"required\": true, \"component\": \"date\"}, {\"field\": \"destination\", \"label\": \"去向地点\", \"required\": true, \"component\": \"input\"}, {\"field\": \"emergencyContact\", \"label\": \"紧急联系人\", \"required\": true, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 1, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '学生请销假默认模板');
INSERT INTO `sc_affair_template` VALUES (2, 2, 'LEAVE_RETURN_STANDARD', '离返校申请', 'LEAVE_RETURN_STANDARD', '离返校申请', 'student', '[{\"field\": \"leaveSchoolDate\", \"label\": \"离校日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"expectedReturnDate\", \"label\": \"预计返校日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"location\", \"label\": \"当前去向\", \"required\": true, \"component\": \"input\"}, {\"field\": \"healthStatus\", \"label\": \"健康状态\", \"options\": [{\"label\": \"良好\", \"value\": \"GOOD\"}, {\"label\": \"需关注\", \"value\": \"WATCH\"}, {\"label\": \"特殊情况\", \"value\": \"SPECIAL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"学工审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 2, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '离返校办理模板');
INSERT INTO `sc_affair_template` VALUES (3, 3, 'SCHOLARSHIP_APPLY', '奖学金申请', 'SCHOLARSHIP_APPLY', '奖学金申请', 'student', '[{\"field\": \"scholarshipType\", \"label\": \"奖项类型\", \"options\": [{\"label\": \"国家奖学金\", \"value\": \"NATIONAL\"}, {\"label\": \"校级奖学金\", \"value\": \"SCHOOL\"}, {\"label\": \"专项奖学金\", \"value\": \"SPECIAL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"awardTerm\", \"label\": \"申报学期\", \"required\": true, \"component\": \"input\"}, {\"field\": \"honorLevel\", \"label\": \"成果/荣誉\", \"required\": true, \"component\": \"input\"}, {\"field\": \"mentorTeacherId\", \"label\": \"指导教师\", \"required\": true, \"component\": \"user-select\", \"optionSource\": \"teacher\"}, {\"field\": \"reason\", \"label\": \"申请陈述\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"teacher_review\", \"stepName\": \"指导教师审核\", \"reviewerField\": \"mentorTeacherId\", \"assignmentType\": \"FORM_FIELD\"}, {\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true,\"termId\":null,\"openWindowEnabled\":false,\"openStartTime\":\"\",\"openEndTime\":\"\",\"notice\":\"请先由学院、辅导员或资助管理老师配置可申请学生范围。\"}', '', '', 3, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '奖学金申报模板');
INSERT INTO `sc_affair_template` VALUES (4, 4, 'GRANT_APPLY', '助学金申请', 'GRANT_APPLY', '助学金申请', 'student', '[{\"field\": \"grantType\", \"label\": \"助学金类型\", \"options\": [{\"label\": \"国家助学金\", \"value\": \"NATIONAL\"}, {\"label\": \"校级助学金\", \"value\": \"SCHOOL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"familyIncome\", \"label\": \"家庭年收入（元）\", \"required\": true, \"component\": \"number\"}, {\"field\": \"hardshipLevel\", \"label\": \"困难等级\", \"options\": [{\"label\": \"特别困难\", \"value\": \"LEVEL_A\"}, {\"label\": \"困难\", \"value\": \"LEVEL_B\"}, {\"label\": \"一般困难\", \"value\": \"LEVEL_C\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"资助中心审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true,\"prerequisiteCategoryCodes\":[\"POVERTY_IDENTIFICATION\"]}', '', '', 4, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '助学金模板');
INSERT INTO `sc_affair_template` VALUES (5, 5, 'LOAN_APPLY', '助学贷款申请', 'LOAN_APPLY', '助学贷款申请', 'student', '[{\"field\": \"loanType\", \"label\": \"贷款类型\", \"options\": [{\"label\": \"国家助学贷款\", \"value\": \"NATIONAL\"}, {\"label\": \"生源地贷款\", \"value\": \"LOCAL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"loanAmount\", \"label\": \"申请金额（元）\", \"required\": true, \"component\": \"number\"}, {\"field\": \"loanTerm\", \"label\": \"贷款期限（年）\", \"required\": true, \"component\": \"number\"}, {\"field\": \"bankName\", \"label\": \"经办银行\", \"required\": false, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"资助中心审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', NULL, NULL, '', '', 5, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '助学贷款模板');
INSERT INTO `sc_affair_template` VALUES (6, 6, 'WORK_STUDY_APPLY', '勤工助学申请', 'WORK_STUDY_APPLY', '勤工助学申请', 'student', '[{\"field\": \"jobPreference\", \"label\": \"岗位意向\", \"required\": true, \"component\": \"input\"}, {\"field\": \"availableHours\", \"label\": \"每周可投入时长\", \"required\": true, \"component\": \"number\"}, {\"field\": \"skillTags\", \"label\": \"技能特长\", \"required\": false, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true,\"termId\":null,\"openWindowEnabled\":false,\"openStartTime\":\"\",\"openEndTime\":\"\",\"requirePublishedJob\":true,\"notice\":\"勤工助学需先发布岗位，学生按岗位进行申请。\"}', '', '', 6, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '勤工助学模板');
INSERT INTO `sc_affair_template` VALUES (7, 7, 'ACTIVITY_APPLY', '活动申请', 'ACTIVITY_APPLY', '活动申请', 'student,teacher', '[{\"field\": \"activityName\", \"label\": \"活动名称\", \"required\": true, \"component\": \"input\"}, {\"field\": \"activityDate\", \"label\": \"活动日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"venue\", \"label\": \"活动地点\", \"required\": true, \"component\": \"input\"}, {\"field\": \"participantCount\", \"label\": \"参与人数\", \"required\": true, \"component\": \"number\"}, {\"field\": \"mentorTeacherId\", \"label\": \"指导教师\", \"required\": true, \"component\": \"user-select\", \"optionSource\": \"teacher\"}, {\"field\": \"reason\", \"label\": \"活动说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"teacher_review\", \"stepName\": \"指导教师审核\", \"reviewerField\": \"mentorTeacherId\", \"assignmentType\": \"FORM_FIELD\"}, {\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 7, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '活动申请模板');
INSERT INTO `sc_affair_template` VALUES (8, 8, 'SUBJECT_COMPETITION_APPLY', '学科竞赛申请', 'SUBJECT_COMPETITION_APPLY', '学科竞赛申请', 'student,teacher', '[{\"field\": \"competitionName\", \"label\": \"竞赛名称\", \"required\": true, \"component\": \"input\"}, {\"field\": \"competitionLevel\", \"label\": \"竞赛级别\", \"options\": [{\"label\": \"校级\", \"value\": \"SCHOOL\"}, {\"label\": \"市级\", \"value\": \"CITY\"}, {\"label\": \"省级\", \"value\": \"PROVINCE\"}, {\"label\": \"国家级\", \"value\": \"NATIONAL\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"competitionDate\", \"label\": \"竞赛时间\", \"required\": true, \"component\": \"date\"}, {\"field\": \"mentorTeacherId\", \"label\": \"指导教师\", \"required\": true, \"component\": \"user-select\", \"optionSource\": \"teacher\"}, {\"field\": \"teamInfo\", \"label\": \"团队成员\", \"required\": false, \"component\": \"textarea\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"teacher_review\", \"stepName\": \"指导教师审核\", \"reviewerField\": \"mentorTeacherId\", \"assignmentType\": \"FORM_FIELD\"}, {\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 8, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '学科竞赛模板');
INSERT INTO `sc_affair_template` VALUES (9, 9, 'TEXTBOOK_APPLY', '教材申请', 'TEXTBOOK_APPLY', '教材申请', 'student,teacher', '[{\"field\": \"textbookType\", \"label\": \"办理类型\", \"options\": [{\"label\": \"教材领用\", \"value\": \"CLAIM\"}, {\"label\": \"教材补领\", \"value\": \"REISSUE\"}, {\"label\": \"教材征订\", \"value\": \"ORDER\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"courseId\", \"label\": \"对应课程\", \"required\": true, \"component\": \"select\", \"optionSource\": \"myCourses\", \"hintText\": \"请选择教材对应的课程\"}, {\"field\": \"isbn\", \"label\": \"ISBN/教材编号\", \"required\": true, \"component\": \"input\", \"hintText\": \"请填写教材封底的ISBN编号\"}, {\"field\": \"quantity\", \"label\": \"数量\", \"required\": true, \"component\": \"number\", \"hintText\": \"每次申请最多10本\"}, {\"field\": \"reason\", \"label\": \"申请说明\", \"required\": false, \"component\": \"textarea\", \"hintText\": \"如为补领请说明原因，征订请说明需求\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"教务审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 9, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '教材模板');
INSERT INTO `sc_affair_template` VALUES (10, 10, 'INNOVATION_PROJECT_APPLY', '创新创业项目申请', 'INNOVATION_PROJECT_APPLY', '创新创业项目申请', 'student,teacher', '[{\"field\": \"projectName\", \"label\": \"项目名称\", \"required\": true, \"component\": \"input\"}, {\"field\": \"projectType\", \"label\": \"项目类型\", \"options\": [{\"label\": \"创新训练\", \"value\": \"INNOVATION\"}, {\"label\": \"创业实践\", \"value\": \"ENTREPRENEURSHIP\"}, {\"label\": \"重点孵化\", \"value\": \"INCUBATION\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"mentorTeacherId\", \"label\": \"指导教师\", \"required\": true, \"component\": \"user-select\", \"optionSource\": \"teacher\"}, {\"field\": \"fundingNeed\", \"label\": \"经费需求（元）\", \"required\": false, \"component\": \"number\"}, {\"field\": \"reason\", \"label\": \"项目说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"teacher_review\", \"stepName\": \"指导教师审核\", \"reviewerField\": \"mentorTeacherId\", \"assignmentType\": \"FORM_FIELD\"}, {\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"创新创业中心审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 10, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '创新创业模板');
INSERT INTO `sc_affair_template` VALUES (11, 11, 'ACADEMIC_STATUS_SUSPEND', '学籍异动-休学', 'ACADEMIC_STATUS_SUSPEND', '休学申请', 'student', '[{\"field\": \"effectiveDate\", \"label\": \"生效日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"expectedResumeDate\", \"label\": \"预计复学日期\", \"required\": false, \"component\": \"date\"}, {\"field\": \"guardianPhone\", \"label\": \"家长联系电话\", \"required\": true, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"异动原因\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"教务审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', 'SUSPENDED', '休学', 11, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '学籍异动休学模板');
INSERT INTO `sc_affair_template` VALUES (12, 11, 'ACADEMIC_STATUS_RESUME', '学籍异动-复学', 'ACADEMIC_STATUS_RESUME', '复学申请', 'student', '[{\"field\": \"effectiveDate\", \"label\": \"生效日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"recoveryProof\", \"label\": \"复学依据\", \"required\": false, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"异动原因\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"教务审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', 'IN_SCHOOL', '在籍在校', 12, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '学籍异动复学模板');
INSERT INTO `sc_affair_template` VALUES (13, 11, 'ACADEMIC_STATUS_TRANSFER_MAJOR', '学籍异动-转专业', 'ACADEMIC_STATUS_TRANSFER_MAJOR', '转专业申请', 'student', '[{\"field\": \"effectiveDate\", \"label\": \"生效日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"targetMajor\", \"label\": \"目标专业\", \"required\": true, \"component\": \"input\"}, {\"field\": \"reason\", \"label\": \"异动原因\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"教务审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', 'TRANSFERRED_MAJOR', '转专业', 13, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '学籍异动转专业模板');
INSERT INTO `sc_affair_template` VALUES (14, 12, 'COMPREHENSIVE_EVALUATION_APPLY', '综测测评申请', 'COMPREHENSIVE_EVALUATION_APPLY', '综测测评申请', 'student', '[{\"field\": \"evaluationTerm\", \"label\": \"评价学期\", \"required\": true, \"component\": \"input\"}, {\"field\": \"achievementSummary\", \"label\": \"德育/竞赛/志愿成果\", \"required\": true, \"component\": \"textarea\"}, {\"field\": \"volunteerHours\", \"label\": \"志愿时长（小时）\", \"required\": false, \"component\": \"number\"}, {\"field\": \"reason\", \"label\": \"补充说明\", \"required\": false, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 14, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '综测测评模板');
INSERT INTO `sc_affair_template` VALUES (15, 13, 'POVERTY_IDENTIFICATION_APPLY', '贫困生认定申请', 'POVERTY_IDENTIFICATION_APPLY', '贫困生认定申请', 'student', '[{\"field\": \"familyIncome\", \"label\": \"家庭年收入（元）\", \"required\": true, \"component\": \"number\"}, {\"field\": \"familyMembers\", \"label\": \"家庭人口\", \"required\": true, \"component\": \"number\"}, {\"field\": \"hardshipLevel\", \"label\": \"困难等级\", \"options\": [{\"label\": \"特别困难\", \"value\": \"LEVEL_A\"}, {\"label\": \"困难\", \"value\": \"LEVEL_B\"}, {\"label\": \"一般困难\", \"value\": \"LEVEL_C\"}], \"required\": true, \"component\": \"select\"}, {\"field\": \"reason\", \"label\": \"认定说明\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"资助中心审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true,\"termId\":null,\"openWindowEnabled\":true,\"openStartTime\":\"\",\"openEndTime\":\"\",\"notice\":\"请在认定窗口期内提交家庭经济困难认定申请。\"}', '', '', 15, '0', 'admin', '2026-03-28 16:21:04', '', NULL, '贫困生认定模板');
INSERT INTO `sc_affair_template` VALUES (16, 1, 'ASK_LEAVE_CANCEL', '销假登记', 'ASK_LEAVE_CANCEL', '销假登记', 'student', '[{\"field\": \"leaveRequestNo\", \"label\": \"原请假编号\", \"required\": true, \"component\": \"select\", \"optionSource\": \"myLeaveRequests\", \"hintText\": \"仅显示已审批通过且尚未销假的请假记录\"}, {\"field\": \"actualReturnDate\", \"label\": \"实际返校日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"cancelRemark\", \"label\": \"销假说明\", \"hintText\": \"如提前返校或返校后补登，请在此说明。\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员确认\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '0', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 2, '0', 'admin', '2026-03-28 20:09:07', '', NULL, '请销假场景下的销假登记模板');
INSERT INTO `sc_affair_template` VALUES (17, 2, 'LEAVE_RETURN_CONFIRM', '返校登记', 'LEAVE_RETURN_CONFIRM', '返校登记', 'student', '[{\"field\": \"leaveRequestNo\", \"label\": \"离校申请编号\", \"required\": true, \"component\": \"select\", \"optionSource\": \"myLeaveReturnRequests\", \"hintText\": \"仅显示已审批通过且尚未登记返校的离校申请\"}, {\"field\": \"returnDate\", \"label\": \"返校日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"travelSummary\", \"label\": \"行程说明\", \"hintText\": \"请填写返校交通方式、返校时间及需要说明的信息。\", \"required\": true, \"component\": \"textarea\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员确认\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}]', '0', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', '', '', 3, '0', 'admin', '2026-03-28 20:09:07', '', NULL, '离返校场景下的返校登记模板');
INSERT INTO `sc_affair_template` VALUES (18, 11, 'ACADEMIC_STATUS_WITHDRAW', '学籍异动-退学', 'ACADEMIC_STATUS_WITHDRAW', '退学申请', 'student', '[{\"field\": \"withdrawType\", \"label\": \"退学类型\", \"required\": true, \"component\": \"select\", \"options\": [{\"label\": \"自愿退学\", \"value\": \"VOLUNTARY\"}, {\"label\": \"学业退学\", \"value\": \"ACADEMIC\"}, {\"label\": \"健康原因\", \"value\": \"HEALTH\"}, {\"label\": \"经济原因\", \"value\": \"FINANCIAL\"}, {\"label\": \"其他\", \"value\": \"OTHER\"}]}, {\"field\": \"effectiveDate\", \"label\": \"生效日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"reason\", \"label\": \"退学原因\", \"required\": true, \"component\": \"textarea\", \"hintText\": \"请详细说明退学原因，包括主要考虑因素及个人规划\"}, {\"field\": \"guardianName\", \"label\": \"监护人姓名\", \"required\": true, \"component\": \"input\"}, {\"field\": \"guardianPhone\", \"label\": \"监护人联系电话\", \"required\": true, \"component\": \"input\", \"hintText\": \"退学手续办理期间需保持畅通\"}, {\"field\": \"guardianOpinion\", \"label\": \"家长/监护人意见\", \"required\": true, \"component\": \"textarea\", \"hintText\": \"请填写家长或监护人对退学的知情及意见情况\"}, {\"field\": \"dormCheckout\", \"label\": \"是否已办理宿舍退宿\", \"required\": true, \"component\": \"select\", \"options\": [{\"label\": \"已办理\", \"value\": \"YES\"}, {\"label\": \"未办理\", \"value\": \"NO\"}]}, {\"field\": \"libraryCleared\", \"label\": \"是否已归还图书馆借阅物品\", \"required\": true, \"component\": \"select\", \"options\": [{\"label\": \"已归还\", \"value\": \"YES\"}, {\"label\": \"未归还/无借阅\", \"value\": \"NO\"}]}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"dept_review\", \"stepName\": \"学院审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"学籍管理部门审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', 'WITHDRAWN', '退学', 14, '0', 'admin', '2026-03-31 10:00:00', '', NULL, '学籍异动退学模板');
INSERT INTO `sc_affair_template` VALUES (19, 11, 'ACADEMIC_STATUS_RETAIN', '学籍异动-保留学籍', 'ACADEMIC_STATUS_RETAIN', '保留学籍申请', 'student', '[{\"field\": \"retainReason\", \"label\": \"保留学籍原因\", \"required\": true, \"component\": \"select\", \"options\": [{\"label\": \"应征入伍\", \"value\": \"MILITARY\"}, {\"label\": \"创业\", \"value\": \"ENTREPRENEURSHIP\"}, {\"label\": \"身体原因\", \"value\": \"HEALTH\"}, {\"label\": \"其他\", \"value\": \"OTHER\"}]}, {\"field\": \"retainDuration\", \"label\": \"申请保留时长\", \"required\": true, \"component\": \"select\", \"options\": [{\"label\": \"1年\", \"value\": \"1\"}, {\"label\": \"2年\", \"value\": \"2\"}], \"hintText\": \"保留学籍一般最长不超过2年\"}, {\"field\": \"effectiveDate\", \"label\": \"生效日期\", \"required\": true, \"component\": \"date\"}, {\"field\": \"reason\", \"label\": \"详细说明\", \"required\": true, \"component\": \"textarea\", \"hintText\": \"请详细说明保留学籍的具体原因及计划返校时间\"}, {\"field\": \"guardianName\", \"label\": \"监护人姓名\", \"required\": true, \"component\": \"input\"}, {\"field\": \"guardianPhone\", \"label\": \"监护人联系电话\", \"required\": true, \"component\": \"input\"}, {\"field\": \"contactAddress\", \"label\": \"保留学籍期间联系地址\", \"required\": true, \"component\": \"input\", \"hintText\": \"请填写保留学籍期间的常住地址，便于学校联系\"}]', '[{\"stepCode\": \"advisor_review\", \"stepName\": \"辅导员审核\", \"reviewerRole\": \"advisor\", \"assignmentType\": \"ROLE\"}, {\"stepCode\": \"admin_review\", \"stepName\": \"学院审核\", \"reviewerRole\": \"admin\", \"assignmentType\": \"ROLE\"}]', '1', '1', '{\"scopeType\":\"ALL\",\"deptIds\":[],\"gradeIds\":[],\"classIds\":[],\"userIds\":[]}', '{\"requireNoPending\":true}', 'RETAINED', '保留学籍', 15, '0', 'admin', '2026-03-31 10:00:00', '', NULL, '学籍异动保留学籍模板');

SET FOREIGN_KEY_CHECKS = 1;
